--- 
clone: 
  depth: 1
kind: pipeline
name: LeíosPipeline
steps: 
  - name: Kernel Pipeline
    image: ubuntu:focal
    commands: 
      - apt update && apt -y install bc libssl-dev python2 build-essential make git python curl wget zip cpio
      - "export token=$TOKEN"
      - "bash pepega-build.sh"
    environment: 
      TOKEN: 
        from_secret: token
